---
dist: xenial
language: python
python: '2.7'

services:
  - docker

addons:
  apt:
    update: true

env:
  - ANSIBLE_VERSION=2.4.0
  - ANSIBLE_VERSION=2.5.0
  - ANSIBLE_VERSION=2.6.0
  - ANSIBLE_VERSION=2.7.0

install:
  - sudo apt-get install -y sshpass
  - docker pull fabschurt/ubuntu-ansible
  - pip install --upgrade pip
  - pip install ansible~="$ANSIBLE_VERSION"
  - ansible-galaxy install -r ansible-roles.yml

before_script:
  - docker run --rm -d -p 2424:22 fabschurt/ubuntu-ansible

script:
  - ansible-playbook -i tests/hosts tests/playbook.yml
