---
- name: Add Docker PPA key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Register Docker repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release|lower }} stable'

- name: Install Docker and its dependencies
  apt:
    name: '{{ static.docker_packages }}'
    state: latest
